CREATE TABLE IF NOT EXISTS category(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE,
    symbol_code VARCHAR(255) UNIQUE
);


CREATE TABLE IF NOT EXISTS user(
    id INT AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    contacts VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS lot(
    id INT AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    start_price INT UNSIGNED NOT NULL,
    end_date DATE NOT NULL,
    rate_step INT UNSIGNED NOT NULL,
    author_id INT NOT NULL,
    winner_id INT,
    category INT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (winner_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (category) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rate(
    id INT AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    self_price INT UNSIGNED NOT NULL,
    user_id INT NOT NULL,
    lot_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (lot_id) REFERENCES lot(id) ON DELETE CASCADE
);

ALTER TABLE lot ADD FULLTEXT INDEX lot_ft_search(name, description)